openapi: 3.0.3
info:
  title: SmartHome - OpenAPI 3.0
  description: ''
  version: 1.0.11
tags:
  - name: device-mng-service
    description: Manage the state of a specific device added by the user.
paths:
  /device/{id}/power:
    post:
      tags:
        - device-mng-service
      summary: Send command to switch between turned on and turned off device state
      description: power switch
      operationId: devicePower
      parameters:
        - name: id
          in: path
          description: ID of device
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid ID supplied
        '404':
          description: Device not found
        '403':
          description: User has no access to device
  /device/{deviceId}/execute/{commandId}:
    post:
      tags:
        - device-mng-service
      summary: Send the existing command to be executed on the device
      description: command executor 
      operationId: executeCommand
      parameters:
        - name: deviceId
          in: path
          description: ID of the device
          required: true
          schema:
            type: integer
        - name: commandId
          in: path
          description: ID of the command
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                commandPayload:
                  type: object
      responses:
        '200':
          description: successful operation
        '404':
          description: device not found / command not found
        '400':
          description: Invalid device ID / Invalid command ID / invalid command payload
  /hub:
    post:
      tags:
        - device-mng-service
      summary: Registers new user hub
      description: hub register 
      operationId: hubRegister
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: integer
                houseId:
                  type: integer
                hub:
                  type: object
                  properties:
                    name:
                      type: string
      responses:
        '200':
          description: successful operation
        '403':
          description: user has no access to house
    get:
      tags:
        - device-mng-service
      summary: get user hub list
      description: hub list 
      operationId: hubList
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    hubId:
                      type: integer
                    hubName: 
                      type: string
                    devices:
                      type: array
                      items:
                        type: object
                        properties:
                          deviceId:
                            type: integer
                          deviceName:
                            type: string
                          commands:
                            type: array
                            items:
                              type: object
                              properties:
                                commandId:
                                  type: integer
                                commandName:
                                  type: string
        '401':
          description: authentication required
  /command/{deviceId}:
    get:
      tags:
        - device-mng-service
      summary: get user command list
      description: command list 
      operationId: commandList
      parameters:
        - name: deviceId
          in: path
          description: ID of device
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    commandId:
                      type: integer
                    deviceId:
                      type: integer
                    commandName: 
                      type: string
                    commandPayloadSchema:
                      type: object
        '404':
          description: command not found